// app/Profile/profileCards.js
export const profileCards = [
    {
        title: "Der Aufstieg und Fall von Benko",
        description: "Benkos Spiel scheint aus zu sein. Aber warum konnte der Milliarden-Spekulant...",
        author: "Peter Pilz",
        date: "Aktualisiert Nov 29",
        comments: 96,
        likes: 2770,
      },
      {
        title: "Eine Linkspartei gewinnt gegen Kickl",
        description: "Herbert Kickl kann noch abgefangen werden. Dazu braucht es allerdings eine...",
        author: "Peter Pilz",
        date: "Aktualisiert Dec 10, 2023",
        comments: 0,
        likes: 0,
      },
      {
        title: "Muss Benko ins Gefängnis?",
        description: "Niemand kann behaupten, dass René Benko ein gewöhnlicher Verbrecher sei...",
        author: "Peter Pilz",
        date: "Aktualisiert Dec 5, 2023",
        comments: 0,
        likes: 0,
      },
      {
        title: "Gusenbauer: Handheben für Benko",
        description: "Gusenbauer scheint Benko zu unterstützen...",
        author: "Peter Pilz",
        date: "Aktualisiert Nov 23, 2023",
        comments: 0,
        likes: 0,
      },
      {
        title: "Staatsanwaltschaft Wien prüft Anfangsverdacht gegen Sobotka",
        description: "Die Staatsanwaltschaft Wien untersucht Sobotka...",
        author: "Peter Pilz",
        date: "Aktualisiert Nov 23, 2023",
        comments: 0,
        likes: 0,
      },
      {
        title: "Pilnacek-Tape: Auslöser Kurz",
        description: "Kurz scheint der Auslöser im Pilnacek-Tape zu sein...",
        author: "Peter Pilz",
        date: "Aktualisiert Nov 22, 2023",
        comments: 0,
        likes: 0,
      },
      {
        title: "Pilnacek-Tape: Ermittlungen gegen Sobotka",
        description: "Ermittlungen gegen Sobotka im Zusammenhang mit dem Pilnacek-Tape...",
        author: "Peter Pilz",
        date: "Aktualisiert Nov 22, 2023",
        comments: 0,
        likes: 0,
      },
      {
        title: "Was Babler braucht: Die Weisheit von Kreisky",
        description: "Babler könnte von der Weisheit von Kreisky profitieren...",
        author: "Peter Pilz",
        date: "Aktualisiert Nov 19, 2023",
        comments: 0,
        likes: 0,
      },
      {
        title: "Die größten Steuersünder im Einkaufswagen",
        description: "Einige große Unternehmen betreiben Steuerflucht...",
        author: "Peter Pilz",
        date: "Aktualisiert Dec 11, 2023",
        comments: 0,
        likes: 0,
      },
      {
        title: "Massaker für die Börse",
        description: "Ein unbekannter Börsenspekulant profitiert vom Massaker der Hamas...",
        author: "Peter Pilz",
        date: "Aktualisiert Dec 8, 2023",
        comments: 0,
        likes: 0,
      },
      {
        title: "Desolidarisierung der Selbstgerechten",
        description: "Die Zerstörung der Links-Fraktion in Deutschland ist Sahra Wagenknecht anzulasten...",
        author: "Peter Pilz",
        date: "Aktualisiert Dec 7, 2023",
        comments: 0,
        likes: 0,
      },
    // Add more profile cards here...
  ];